const players = [
	{
		id: 1,
		name: 'Flowax',
		zones: {
			NEILOPOLIS: 0,
			HEDAK: 0,
			'VALLEE ARC': 0,
			'FORET BRUMEUSE': 0,
			'COTE ENSOLEILLEE': 0,
			'VOLCAN GRONDANT': 0,
			'CANYON DU TONNERRE': 0,
			'DESERT SENENITE': 0,
			'PLAINES ETOILEES': 0,
			'VALLEE CDL': 0,
			'MONTAGNE ENNEIGEE': 0,
			"ILE D'AUBEVILLE": 0,
			'PLATEAU DESTINEE': 0,
			'MARECAGE OUBLIE': 0,
			'LAC CRISTAL': 0,
			'TUMULUS DU DRAGON': 0,
		},
	},
	{
		id: 2,
		name: 'Biggie',
		zones: {
			NEILOPOLIS: 0,
			HEDAK: 0,
			'VALLEE ARC': 0,
			'FORET BRUMEUSE': 0,
			'COTE ENSOLEILLEE': 0,
			'VOLCAN GRONDANT': 0,
			'CANYON DU TONNERRE': 0,
			'DESERT SENENITE': 0,
			'PLAINES ETOILEES': 0,
			'VALLEE CDL': 0,
			'MONTAGNE ENNEIGEE': 0,
			"ILE D'AUBEVILLE": 0,
			'PLATEAU DESTINEE': 0,
			'MARECAGE OUBLIE': 0,
			'LAC CRISTAL': 0,
			'TUMULUS DU DRAGON': 0,
		},
	},
	{
		id: 3,
		name: 'Bamlet',
		zones: {
			NEILOPOLIS: 0,
			HEDAK: 0,
			'VALLEE ARC': 0,
			'FORET BRUMEUSE': 0,
			'COTE ENSOLEILLEE': 0,
			'VOLCAN GRONDANT': 0,
			'CANYON DU TONNERRE': 0,
			'DESERT SENENITE': 0,
			'PLAINES ETOILEES': 0,
			'VALLEE CDL': 0,
			'MONTAGNE ENNEIGEE': 0,
			"ILE D'AUBEVILLE": 0,
			'PLATEAU DESTINEE': 0,
			'MARECAGE OUBLIE': 0,
			'LAC CRISTAL': 0,
			'TUMULUS DU DRAGON': 0,
		},
	},
];

module.exports = players;
